### ISSUE TITLE
Likely problem in replicate collapsing. Discovered discrepancy between DEseq and our collapsed counts

### ISSUE THREAD

**Issue by cancenik** [brendan4/DBA_project#11]

**Comment by brendan4** [comment]
The order of count data was not matched to the pheno.data before collapsing which was assumed by the code. Count data were matched to pheno.data before DEseq analysis. When making my comparison to DEseq's collapse function, the collapsing code was at the bottom of the script (past the DEseq analysis meaning the count and pheno.data had been matched already and values were correct). Moving the collapsing code to above the propd analysis (which is before DEseq analysis) yielded the error since now count and pheno.data did not match in order.
